namespace MTA.Core.Common.Enums
{
    public enum LogAction
    {
        ChatH = 1,
        ChatI = 2,
        ChatA = 3,
        AdminCommands = 4,
        Anticheat = 5,
        Vehicles = 6,
        ChatIC = 7,
        ChatB = 8,
        ChatR = 9,
        ChatD = 10,
        ChatF = 11,
        ChatMe = 12,
        ChatDistrict = 13,
        ChatDo = 14,
        ChatPm = 15,
        ChatGov = 16,
        ChatDon = 17,
        ChatO = 18,
        ChatS = 19,
        ChatM = 20,
        ChatW = 21,
        ChatC = 22,
        ChatN = 23,
        SupporterChatG = 24,
        TransferMoney = 25,
        PremiumPanel = 26,
        CharacterConnections = 27,
        RoadBlockades = 28,
        PhoneCalls = 29,
        PhoneSms = 30,
        OpenCloseVehicles = 31,
        Api = 32,
        TransferPanelData = 33,
        Deaths = 34,
        FactionsPanel = 35,
        AmmunationShops = 36,
        Interiors = 37,
        Reports = 38,
        MoveItems = 39,
        ChatAme = 40
    }
}